repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: 'ip2region_v4.xdb'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args:
          - '--config'
          - 'backend/.ruff.toml'
          - '--fix'
          - '--unsafe-fixes'
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.14
    hooks:
      - id: uv-lock
      - id: uv-export
        args:
          - '-o'
          - 'requirements.txt'
          - '--no-hashes'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.18.2'
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.0
        args:
          - '--config-file'
          - 'backend/.mypy.ini'
          - '--python-executable'
          - './.venv/bin/python'
