# Global options:

[mypy]

# import discovery
exclude_gitignore = True
follow_imports = silent

# Disallow any unimported
disallow_any_unimported = True

# Untyped definitions and calls
disallow_untyped_defs = True

# Configuring warings
warn_return_any = True
warn_unreachable = True

# Miscellaneous
warn_unused_configs = True
no_implicit_optional = True
show_error_codes = True

# Plugins
plugins = pydantic.mypy

# Custom module options:

# Third-party library options:

;[mypy-sqlalchemy.*]
;ignore_missing_imports = True

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-fast_captcha.*]
ignore_missing_imports = True

[mypy-ip2loc.*]
ignore_missing_imports = True

[mypy-user_agents.*]
ignore_missing_imports = True


# Plugin options:

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
